# Generated by Django 6.0.5 on 2026-06-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_security_fields'),
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='config_center.campus', verbose_name='所属校区'),
        ),
    ]
