# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_meter_utility_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(choices=[('personal', '个人'), ('company', '单位')], default='personal', max_length=20, verbose_name='抬头类型')),
                ('title_name', models.CharField(max_length=200, verbose_name='发票抬头名称')),
                ('tax_no', models.CharField(blank=True, default='', max_length=50, verbose_name='纳税人识别号')),
                ('email', models.EmailField(max_length=200, verbose_name='接收邮箱')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_titles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'db_table': 'invoice_titles',
                'verbose_name': '发票抬头',
                'verbose_name_plural': '发票抬头',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=40, unique=True, verbose_name='退费单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请退费金额')),
                ('reason', models.CharField(max_length=500, verbose_name='退费原因')),
                ('attachment_url', models.CharField(blank=True, default='', max_length=500, verbose_name='附件链接')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('review_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recharge_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='billing.rechargerecord', verbose_name='关联充值记录')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'db_table': 'refund_requests',
                'verbose_name': '退费申请',
                'verbose_name_plural': '退费申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=40, unique=True, verbose_name='开票申请单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='开票总金额')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('issued', '已开具'), ('rejected', '已驳回'), ('void', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='电子发票号')),
                ('download_url', models.CharField(blank=True, default='', max_length=500, verbose_name='发票下载链接')),
                ('review_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='处理备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_requests', to='refund_invoice.invoicetitle', verbose_name='发票抬头')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'db_table': 'invoice_requests',
                'verbose_name': '开票申请',
                'verbose_name_plural': '开票申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='开票金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invoice_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refund_invoice.invoicerequest', verbose_name='开票申请')),
                ('recharge_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.rechargerecord', verbose_name='充值记录')),
            ],
            options={
                'db_table': 'invoice_request_items',
                'verbose_name': '开票申请明细',
                'verbose_name_plural': '开票申请明细',
            },
        ),
    ]
