# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_freeze_logs'),
        ('dormitory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', '水费'), ('electricity', '电费')], max_length=20, unique=True, verbose_name='费用类型')),
                ('strategy_type', models.CharField(choices=[('flat', '单一单价'), ('tiered', '分段计价')], default='flat', max_length=20, verbose_name='计价方式')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='基础单价')),
                ('tiers', models.JSONField(blank=True, default=list, verbose_name='分段配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'price_strategies',
                'verbose_name': '价格策略',
                'verbose_name_plural': '价格策略',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', '水费'), ('electricity', '电费')], max_length=20, verbose_name='抄表类型')),
                ('period_start', models.DateField(verbose_name='周期开始日期')),
                ('period_end', models.DateField(verbose_name='周期结束日期')),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='上期表底')),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本期表底')),
                ('usage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期用量')),
                ('source', models.CharField(choices=[('admin', '管理员录入'), ('external', '外部系统'), ('auto', '自动生成')], default='admin', max_length=20, verbose_name='数据来源')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='dormitory.room', verbose_name='房间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='关联学生')),
            ],
            options={
                'db_table': 'meter_readings',
                'verbose_name': '抄表记录',
                'verbose_name_plural': '抄表记录',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(condition=models.Q(user__isnull=True), fields=('room', 'category', 'period_start', 'period_end'), name='unique_room_meter_reading_per_period'),
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=40, unique=True, verbose_name='账单编号')),
                ('category', models.CharField(choices=[('water', '水费'), ('electricity', '电费')], max_length=20, verbose_name='费用类型')),
                ('period_start', models.DateField(verbose_name='周期开始日期')),
                ('period_end', models.DateField(verbose_name='周期结束日期')),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='上期表底')),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本期表底')),
                ('usage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='用量')),
                ('price_detail', models.JSONField(blank=True, default=dict, verbose_name='价格明细')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='单价')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基础金额')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='滞纳金金额')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='应缴总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已缴金额')),
                ('due_date', models.DateField(verbose_name='最后缴费日期')),
                ('status', models.CharField(choices=[('pending', '待缴'), ('paid', '已缴'), ('void', '已作废'), ('merged', '已合并'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('consumption_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bill', to='billing.consumptionrecord', verbose_name='关联消费记录')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.meterreading', verbose_name='关联抄表记录')),
                ('parent_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_bills', to='billing.utilitybill', verbose_name='合并至的账单')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='dormitory.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to=settings.AUTH_USER_MODEL, verbose_name='学生用户')),
            ],
            options={
                'db_table': 'utility_bills',
                'verbose_name': '水电账单',
                'verbose_name_plural': '水电账单',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
