# Generated by Django 6.0.5 on 2026-06-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_meter_utility_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechangelog',
            name='change_type',
            field=models.CharField(choices=[('recharge', '充值入账'), ('consumption', '消费扣费'), ('freeze', '账户冻结'), ('unfreeze', '账户解冻'), ('adjust', '余额调整'), ('refund', '退费扣减')], max_length=20),
        ),
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('dataset', models.CharField(max_length=50)),
                ('dimensions', models.JSONField(default=list)),
                ('measures', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('chart_type', models.CharField(default='bar', max_length=30)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_reports',
                'ordering': ['-updated_at'],
            },
        ),
    ]
