import { COMMAND_CATEGORIES } from './registry'

export default [
  {
    id: 'dashboard',
    title: '返回主页',
    description: '跳转到系统仪表盘首页',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['home', '首页', '仪表盘', 'dashboard'],
    icon: '🏠',
    handler: ({ router }) => router.push('/dashboard'),
  },
  {
    id: 'logout',
    title: '退出登录',
    description: '清除会话并返回登录页',
    category: COMMAND_CATEGORIES.action,
    keywords: ['退出', '登出', 'logout', 'sign out'],
    icon: '🚪',
    handler: ({ authStore, router }) => {
      authStore.clearSession()
      router.push('/login')
    },
  },
  {
    id: 'goto.analytics',
    title: '数据看板',
    description: '打开管理员数据分析面板',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['分析', '统计', '报表', 'analytics', '数据看板'],
    icon: '📊',
    adminOnly: true,
    handler: ({ router }) => router.push('/analytics'),
  },
  {
    id: 'goto.reports',
    title: '自定义报表',
    description: '打开自定义报表构建器',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['报表', 'report', 'builder'],
    icon: '📋',
    adminOnly: true,
    handler: ({ router }) => router.push('/reports'),
  },
  {
    id: 'goto.config',
    title: '配置中心',
    description: '打开系统配置管理',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['配置', 'config', '设置'],
    icon: '⚙️',
    adminOnly: true,
    handler: ({ router }) => router.push('/config-center'),
  },
  {
    id: 'goto.campus',
    title: '校区管理',
    description: '打开校区信息管理',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['校区', 'campus', '学校'],
    icon: '🏫',
    adminOnly: true,
    handler: ({ router }) => router.push('/campus-manage'),
  },
  {
    id: 'goto.collection',
    title: '催缴管理',
    description: '打开催缴中心管理欠费账单',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['催缴', '欠费', 'collection'],
    icon: '⏰',
    adminOnly: true,
    handler: ({ router }) => router.push('/collection-manage'),
  },
  {
    id: 'goto.reminders',
    title: '提醒中心',
    description: '查看系统提醒事项',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['提醒', 'reminder', '闹钟'],
    icon: '🔔',
    handler: ({ router }) => router.push('/reminders'),
  },
  {
    id: 'goto.activities',
    title: '校园活动',
    description: '浏览和报名校园活动',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['活动', 'activities', '报名'],
    icon: '🎉',
    handler: ({ router }) => router.push('/activities'),
  },
  {
    id: 'goto.activity-manage',
    title: '活动管理',
    description: '管理校园活动（管理员）',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['活动管理', 'activity manage'],
    icon: '🎛️',
    adminOnly: true,
    handler: ({ router }) => router.push('/activities/manage'),
  },
  {
    id: 'goto.data-center',
    title: '数据中心',
    description: '数据导入导出任务管理',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['数据', '导入', '导出', 'data', 'import', 'export'],
    icon: '💾',
    adminOnly: true,
    handler: ({ router }) => router.push('/data-center'),
  },
  {
    id: 'goto.my-refunds',
    title: '我的退款',
    description: '查看退款申请记录',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['退款', 'refund'],
    icon: '💰',
    handler: ({ router }) => router.push('/my-refunds'),
  },
  {
    id: 'goto.my-invoices',
    title: '我的发票',
    description: '查看和申请发票',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['发票', 'invoice'],
    icon: '🧾',
    handler: ({ router }) => router.push('/my-invoices'),
  },
  {
    id: 'goto.refund-approval',
    title: '退款审批',
    description: '审批学生退款申请',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['退款审批', 'refund approval'],
    icon: '✅',
    adminOnly: true,
    handler: ({ router }) => router.push('/refund-approval'),
  },
  {
    id: 'goto.invoice-processing',
    title: '发票处理',
    description: '处理发票申请',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['发票处理', 'invoice processing'],
    icon: '📑',
    adminOnly: true,
    handler: ({ router }) => router.push('/invoice-processing'),
  },
  {
    id: 'goto.invoice-titles',
    title: '发票抬头',
    description: '管理发票抬头信息',
    category: COMMAND_CATEGORIES.navigation,
    keywords: ['发票抬头', 'invoice title'],
    icon: '📝',
    handler: ({ router }) => router.push('/invoice-titles'),
  },
]
