# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动介绍')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='人数上限')),
                ('require_approval', models.BooleanField(default=False, verbose_name='是否需要审核报名')),
                ('require_payment', models.BooleanField(default=False, verbose_name='是否需要扣费')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='活动费用')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('published', '已发布'),
                            ('ongoing', '进行中'),
                            ('ended', '已结束'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='活动状态',
                    ),
                ),
                ('check_in_code', models.CharField(blank=True, default='', max_length=16, verbose_name='签到码')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                (
                    'publisher',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='published_activities',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='发布人',
                    ),
                ),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'verbose_name': '校园活动',
                'verbose_name_plural': '校园活动',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', '待审核'),
                            ('approved', '已报名'),
                            ('rejected', '已驳回'),
                            ('checked_in', '已签到'),
                            ('cancelled', '已取消'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='报名状态',
                    ),
                ),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已支付金额')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('review_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='registrations',
                        to='activities.activity',
                        verbose_name='活动',
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_activity_registrations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='审核人',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='activity_registrations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='报名用户',
                    ),
                ),
            ],
            options={
                'db_table': 'activity_registrations',
                'ordering': ['-registered_at'],
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
            },
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'rating',
                    models.PositiveSmallIntegerField(
                        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                        verbose_name='评分',
                    ),
                ),
                ('content', models.TextField(blank=True, default='', max_length=1000, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='activities.activity',
                        verbose_name='活动',
                    ),
                ),
                (
                    'registration',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='review',
                        to='activities.activityregistration',
                        verbose_name='关联报名记录',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='activity_reviews',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='评价用户',
                    ),
                ),
            ],
            options={
                'db_table': 'activity_reviews',
                'ordering': ['-created_at'],
                'verbose_name': '活动评价',
                'verbose_name_plural': '活动评价',
            },
        ),
        migrations.AddConstraint(
            model_name='activityregistration',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_registration_per_user'),
        ),
        migrations.AddConstraint(
            model_name='activityreview',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_review_per_user'),
        ),
    ]
