# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notice_type',
            field=models.CharField(
                choices=[
                    ('announcement', '系统公告'),
                    ('order', '订单通知'),
                    ('security', '安全通知'),
                    ('system', '系统消息'),
                    ('billing', '账单通知'),
                ],
                default='system',
                max_length=20,
            ),
        ),
    ]
