# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='楼栋名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['name'],
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=32, verbose_name='房间号')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='房间容量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.building', verbose_name='所属楼栋')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['building__name', 'room_number'],
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('unbound_at', models.DateTimeField(blank=True, null=True, verbose_name='解绑时间')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dormitory.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL, verbose_name='学生用户')),
            ],
            options={
                'db_table': 'room_assignments',
                'ordering': ['-bound_at'],
                'verbose_name': '房间绑定记录',
                'verbose_name_plural': '房间绑定记录',
            },
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.UniqueConstraint(fields=['user'], condition=models.Q(('unbound_at__isnull', True)), name='unique_active_assignment_per_user'),
        ),
    ]
