# Generated by Django 6.0.5 on 2026-06-07 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('low_balance', '余额低于阈值'), ('no_recharge_predicted_overdue', '本月未充值且预计欠费'), ('bill_due_soon', '未缴账单临近到期'), ('bill_overdue', '未缴账单逾期')], max_length=40, verbose_name='触发类型')),
                ('trigger_key', models.CharField(help_text='同一学生同一触发条件的唯一键，用于幂等控制', max_length=128, verbose_name='触发幂等键')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('resolved_auto', '自动解决'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('current_channel', models.CharField(choices=[('inapp', '站内通知'), ('email', '邮件通知'), ('parent', '家长通知'), ('admin_ticket', '管理员工单')], default='inapp', max_length=30, verbose_name='当前通知渠道')),
                ('escalation_level', models.IntegerField(default=0, help_text='0=站内, 1=邮件, 2=家长, 3=管理员工单', verbose_name='升级层级')),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='上次升级时间')),
                ('title', models.CharField(max_length=200, verbose_name='提醒标题')),
                ('content', models.TextField(verbose_name='提醒内容')),
                ('related_bill_id', models.IntegerField(blank=True, null=True, verbose_name='关联账单ID')),
                ('threshold_snapshot', models.JSONField(blank=True, default=dict, verbose_name='触发时阈值快照')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_note', models.CharField(blank=True, default='', max_length=500, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reminders', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='学生用户')),
            ],
            options={
                'verbose_name': '催缴提醒',
                'verbose_name_plural': '催缴提醒',
                'db_table': 'reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('inapp', '站内通知'), ('email', '邮件通知'), ('parent', '家长通知'), ('admin_ticket', '管理员工单')], max_length=30, verbose_name='通知渠道')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_successful', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('notification_id', models.IntegerField(blank=True, null=True, verbose_name='关联站内通知ID')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reminder.reminder', verbose_name='关联提醒')),
            ],
            options={
                'verbose_name': '提醒发送事件',
                'verbose_name_plural': '提醒发送事件',
                'db_table': 'reminder_events',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReminderExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exempted', models.BooleanField(default=False, verbose_name='是否免除所有催缴')),
                ('exempted_at', models.DateTimeField(blank=True, null=True, verbose_name='设置时间')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='免除原因')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间（空为永久）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exempted_students', to=settings.AUTH_USER_MODEL, verbose_name='设置人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_exemption', to=settings.AUTH_USER_MODEL, verbose_name='学生用户')),
            ],
            options={
                'verbose_name': '学生催缴免除',
                'verbose_name_plural': '学生催缴免除',
                'db_table': 'student_reminder_exemptions',
            },
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'stopped'])), fields=('user', 'trigger_key'), name='unique_active_reminder_per_trigger'),
        ),
    ]
