# Generated by Django 6.0.5 on 2026-06-07 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_username', models.CharField(blank=True, default='', max_length=150, verbose_name='操作人用户名')),
                ('operator_role', models.CharField(blank=True, default='', max_length=50, verbose_name='操作人角色')),
                ('category', models.CharField(choices=[('user', '用户管理'), ('role', '角色变更'), ('order', '订单操作'), ('wallet', '钱包操作'), ('auth', '认证安全'), ('config', '配置变更'), ('data', '数据操作'), ('other', '其他操作')], default='other', max_length=30, verbose_name='操作分类')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login_success', '登录成功'), ('login_failed', '登录失败'), ('logout', '登出'), ('password_reset', '密码重置'), ('password_change', '密码修改'), ('approve', '审核通过'), ('reject', '审核驳回'), ('submit', '提交'), ('freeze', '冻结'), ('unfreeze', '解冻'), ('export', '导出'), ('import', '导入'), ('other', '其他')], default='other', max_length=50, verbose_name='操作动作')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='操作状态')),
                ('target_type', models.CharField(blank=True, default='', max_length=100, verbose_name='目标对象类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=100, verbose_name='目标对象ID')),
                ('target_display', models.CharField(blank=True, default='', max_length=255, verbose_name='目标对象描述')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='变更前数据摘要')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='变更后数据摘要')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='用户代理')),
                ('request_path', models.CharField(blank=True, default='', max_length=255, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='是否可疑')),
                ('suspicious_reasons', models.JSONField(blank=True, default=list, verbose_name='可疑原因列表')),
                ('hash_value', models.CharField(blank=True, default='', max_length=64, verbose_name='日志哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'action'], name='audit_logs_categor_567be3_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'), models.Index(fields=['operator_id'], name='audit_logs_operato_37782c_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'), models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx'), models.Index(fields=['is_suspicious'], name='audit_logs_is_susp_5b7585_idx'), models.Index(fields=['status'], name='audit_logs_status_515e02_idx')],
            },
        ),
    ]
