# Generated by Django 6.0.5 on 2026-06-07 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='校区名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='校区编码')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='校区地址')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='备注说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区',
                'db_table': 'campuses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, verbose_name='配置分组')),
                ('key', models.CharField(max_length=100, verbose_name='配置键')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('decimal', '小数'), ('boolean', '布尔值'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='值类型')),
                ('default_value', models.TextField(blank=True, default='', verbose_name='全局默认值')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最小值(数值型)')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最大值(数值型)')),
                ('regex_pattern', models.CharField(blank=True, default='', max_length=500, verbose_name='正则校验(字符串)')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='可选值列表')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='配置说明')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置项定义',
                'verbose_name_plural': '配置项定义',
                'db_table': 'config_keys',
                'ordering': ['group', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('group', 'key'), name='unique_config_group_key')],
            },
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='变更前值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='变更后值')),
                ('changed_by_name', models.CharField(blank=True, default='', max_length=150, verbose_name='变更人用户名(冗余)')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='变更备注')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_center.campus', verbose_name='校区')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='config_center.configkey', verbose_name='配置项')),
            ],
            options={
                'verbose_name': '配置变更日志',
                'verbose_name_plural': '配置变更日志',
                'db_table': 'config_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='config_center.campus', verbose_name='校区(空为全局默认)')),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='config_center.configkey', verbose_name='配置项')),
            ],
            options={
                'verbose_name': '配置值',
                'verbose_name_plural': '配置值',
                'db_table': 'config_values',
                'ordering': ['config_key__group', 'config_key__sort_order', 'campus__code'],
                'constraints': [models.UniqueConstraint(fields=('config_key', 'campus'), name='unique_config_value_per_campus')],
            },
        ),
    ]
